helm install mysql-exporter prometheus-community/prometheus-mysql-exporter \
  --namespace cattle-monitoring-system \
  --set mysql.user=root \
  --set mysql.pass=rootpassword \
  --set mysql.host=mysql.default.svc.cluster.local \
  --set mysql.port=3306

kubectl apply -f - <<EOF 
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-servicemonitor
  namespace: cattle-monitoring-system
  labels:
    release: rancher-monitoring-operator # Prometheus Operator의 인스턴스 이름과 일치해야 함
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mysql-exporter # Helm 설치 시 생성된 Exporter의 Label
      app.kubernetes.io/name: prometheus-mysql-exporter # Helm Chart 이름
  namespaceSelector:
    matchNames:
      - cattle-monitoring-system
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics

EOF
